"""
Write one Slurm submit file per system size, plus a submit_all.sh driver.

Each size gets its own job name, log directory, data directory and --array range, so all
the samples of one size land in the same place. The array ranges are derived from the same
config that generate_jobs.py uses, so the line numbers always agree with jobs.txt.

Run generate_jobs.py first, then this, then ./submit_all.sh
"""

import math
import stat
from pathlib import Path

import config

parameters = config.parameters_M_transition
here = Path(__file__).resolve().parent

size_vec = parameters['size_vec']
Nsamples = parameters['Nsamples']
NM = parameters['NM']
optimize_theta = parameters['optimize_theta']
Ntheta = parameters['Ntheta'] if optimize_theta else 1
cpus_per_task = parameters.get('cpus_per_task', 8)

# Cost model, measured on 11 cores (see the comment block at the bottom of this file).
# The Hilbert dimension is D = 4 L^2 and each M point does two dense eigh plus a handful of
# dense D x D matmuls, so time ~ D^3 ~ L^6 and peak memory ~ D^2 ~ L^4
SECONDS_PER_POINT_AT_L28 = 24.45
PEAK_GB_BASELINE = 0.12         # interpreter + kwant, independent of L
PEAK_GB_PER_L4 = 3072e-9        # ~12 live D x D complex128 arrays
MEM_SAFETY = 1.5
TIME_SAFETY = 3.0

# Each extra candidate angle is one eigenvalue-only solve, measured at 0.39 of a full
# eigendecomposition, on top of the two full ones every point already pays
EIGVALSH_OVER_EIGH = 0.39
theta_cost_factor = 1.0 if Ntheta == 1 else (2. + EIGVALSH_OVER_EIGH * Ntheta) / 2.

MEM_LADDER_GB = [2, 4, 6, 8, 12, 16, 24, 32, 48, 64, 96, 128, 192, 256]
TIME_LADDER_HOURS = [0.5, 1, 2, 4, 6, 12, 24, 48, 72, 120, 168]


def predicted_peak_gb(L):
    return PEAK_GB_BASELINE + PEAK_GB_PER_L4 * L ** 4


def predicted_scan_seconds(L):
    return NM * SECONDS_PER_POINT_AT_L28 * (L / 28) ** 6 * theta_cost_factor


def round_up(value, ladder):
    for step in ladder:
        if value <= step:
            return step
    return ladder[-1]


def format_walltime(hours):
    total_minutes = int(round(hours * 60))
    days, rem = divmod(total_minutes, 24 * 60)
    hh, mm = divmod(rem, 60)
    return f'{days}-{hh:02d}:{mm:02d}:00'


TEMPLATE = """#!/bin/bash

# Generated by generate_submits.py -- edit that file, not this one.
# Submit with:
#       sbatch {submit_name}
#
# System size L={L}: {Nsamples} disorder samples, lines {start}-{end} of jobs.txt.
# Estimated {scan_human} per sample and ~{peak_gb:.2f} GB peak RSS (measured scaling,
# see generate_submits.py); the requests below carry a {mem_safety}x memory and
# {time_safety}x walltime margin on top of that.
# Angle handling: {theta_note}

#SBATCH --job-name={job_name}
#SBATCH --time={walltime}
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task={cpus}
#SBATCH --mem={mem_gb}G

#SBATCH --output={log_dir}/%x_%N_%a.o.txt
#SBATCH --error={log_dir}/%x_%N_%a.e.txt
#SBATCH --array={start}-{end}

# Uncomment if the environment built by install_env.sh is not already active on the nodes
# source "$(conda info --base)/etc/profile.d/conda.sh"
# conda activate local-markers

# The linear algebra is threaded, not the job: one task using all the allocated cores.
# --mem above is the total for the task, not per core, because these threads share one
# set of matrices rather than each holding their own
export OMP_NUM_THREADS={cpus}
export MKL_NUM_THREADS={cpus}
export OPENBLAS_NUM_THREADS={cpus}

python M_transition_cluster.py --line=$SLURM_ARRAY_TASK_ID -M="{data_dir}" -f="jobs.txt"
"""

theta_note = (f'{Ntheta} candidates on [0, theta_k], costing {theta_cost_factor:.2f}x'
              if Ntheta > 1 else 'fixed at the analytical theta_k')

submit_names = []
print(f'optimize_theta={optimize_theta}, Ntheta={Ntheta} '
      f'-> runtime factor {theta_cost_factor:.2f}x\n')
print(f'{"L":>4} {"lines":>12} {"mem":>7} {"walltime":>12} {"est/sample":>12} {"est peak":>10}')
for id_L, L in enumerate(size_vec):
    start = id_L * Nsamples
    end = start + Nsamples - 1

    peak_gb = predicted_peak_gb(L)
    mem_gb = round_up(MEM_SAFETY * peak_gb, MEM_LADDER_GB)

    scan_seconds = predicted_scan_seconds(L)
    walltime_hours = round_up(TIME_SAFETY * scan_seconds / 3600, TIME_LADDER_HOURS)

    if scan_seconds < 90:
        scan_human = f'{scan_seconds:.0f} s'
    elif scan_seconds < 5400:
        scan_human = f'{scan_seconds / 60:.0f} min'
    else:
        scan_human = f'{scan_seconds / 3600:.1f} h'

    job_name = f'M_transition_{L}'
    log_dir = f'logs-{L}'
    data_dir = f'data-{L}'
    submit_name = f'submit_{L}'

    # Slurm will not create these, and a missing log directory makes the array task fail
    # before it ever reaches python
    (here / log_dir).mkdir(exist_ok=True)
    (here / data_dir).mkdir(exist_ok=True)

    submit_path = here / submit_name
    submit_path.write_text(TEMPLATE.format(
        submit_name=submit_name, L=L, Nsamples=Nsamples, start=start, end=end,
        scan_human=scan_human, peak_gb=peak_gb, mem_safety=MEM_SAFETY, time_safety=TIME_SAFETY,
        job_name=job_name, walltime=format_walltime(walltime_hours), cpus=cpus_per_task,
        mem_gb=mem_gb, log_dir=log_dir, data_dir=data_dir, theta_note=theta_note))
    submit_names.append(submit_name)

    print(f'{L:>4} {f"{start}-{end}":>12} {f"{mem_gb}G":>7} '
          f'{format_walltime(walltime_hours):>12} {scan_human:>12} {f"{peak_gb:.2f} GB":>10}')

all_path = here / 'submit_all.sh'
all_path.write_text('#!/bin/bash\n\n# Generated by generate_submits.py\n\n'
                    + ''.join(f'sbatch {name}\n' for name in submit_names))
all_path.chmod(all_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

print(f'\nWrote {len(submit_names)} submit files and submit_all.sh')

# Cost model provenance
# --------------------
# Peak RSS was measured end to end for one point at L = 8, 12, 16, 20, 24, 28 and fits
#     peak[GB] = 0.12 + 3072e-9 * L^4
# to better than 2% over that range (e.g. L=28 predicted 2.01 GB, measured 1.98 GB). The L^4
# comes from ~12 live D x D complex128 arrays with D = 4 L^2.
#
# Wall time per point over the same range follows the expected L^6, anchored at 24.45 s per
# point for L=28 on 11 cores, and the theta scan multiplies it by the factor above (an
# eigenvalue-only solve measured at 0.39 of a full eigh, at D = 1500 and 2500). Cluster cores
# will differ, which is what the TIME_SAFETY factor absorbs -- check a short run before
# trusting the large sizes.
